# Generated by Django 3.2.3 on 2021-06-03 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_registro', '0003_auto_20210602_0242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('correo', models.EmailField(max_length=254)),
                ('twitter', models.CharField(blank=True, max_length=35, null=True)),
            ],
        ),
    ]
