# Generated by Django 3.2.3 on 2021-06-10 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_registro', '0006_auto_20210610_0224'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('conferencia', 'participante')},
        ),
    ]
