# Generated by Django 3.2.3 on 2021-06-17 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_registro', '0007_alter_asistencia_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencia',
            name='duracion',
            field=models.SmallIntegerField(default=2),
        ),
    ]
