# Generated by Django 3.2.3 on 2021-06-18 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_registro', '0008_conferencia_duracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
