# Generated by Django 3.2.3 on 2021-06-22 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_registro', '0009_alter_participante_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencista',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='conferencistas'),
        ),
    ]
